version: "3"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "3000:3000"
    networks:
      - appnetwork
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    networks:
      - appnetwork
    ports:
      - "27017:27017"
  mongo_seed:
    image: mongo
    links:
      - mongo
    volumes:
      - ./mongo-seed:/mongo-seed
    command:
       /mongo-seed/import.sh
    networks:
      - appnetwork

networks:
  appnetwork: